name: CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run tests (bijv. pytest)
        run: |
          if [ -f requirements.txt ]; then pip install pytest; fi
          pytest || echo "No tests found"
      - name: Run Bandit (SAST)
        run: |
          pip install bandit
          bandit -r .
  - name: Check dependencies (Safety)
    run: |
      pip install safety
      safety check --full-report
  - name: Secret scanning (Gitleaks)
    run: |
      curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks_linux_x64.tar.gz | tar xz
      ./gitleaks detect --no-git -s . 
